import { PrismaClient, UserRole } from '@prisma/client';
import * as bcrypt from 'bcrypt';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const BCRYPT_SALT = 12;

async function main() {
  console.log('🌱 Iniciando seed de PRODUÇÃO do banco de dados...\n');
  console.log('⚠️  ATENÇÃO: Este script apagará todos os dados do banco de dados se houver!\n');

  // Limpiar dados existentes ordenados para não quebrar Constraints de Foreign Keys
  await prisma.$transaction([
    prisma.appointmentService.deleteMany(),
    prisma.appointmentProduct.deleteMany(),
    prisma.invoiceItem.deleteMany(),
    prisma.orderItem.deleteMany(),
    prisma.barberCommission.deleteMany(),
    prisma.agendaLock.deleteMany(),
    prisma.blockedTime.deleteMany(),
    prisma.review.deleteMany(),
    prisma.notificationLog.deleteMany(),
    prisma.productStockMovement.deleteMany(),
    prisma.serviceDisabledPeriod.deleteMany(),
    prisma.serviceProductAnalytics.deleteMany(),
    prisma.serviceOrder.deleteMany(),
    prisma.invoice.deleteMany(),
    prisma.appointment.deleteMany(),
    prisma.dailyCashFlow.deleteMany(),
    prisma.expense.deleteMany(),
    prisma.fixedCost.deleteMany(),
    prisma.supplyItem.deleteMany(),
    prisma.address.deleteMany(),
    prisma.favoriteBarbershop.deleteMany(),
    prisma.product.deleteMany(),
    prisma.service.deleteMany(),
    prisma.plan.deleteMany(),
    prisma.barber.deleteMany(),
    prisma.client.deleteMany(),
    prisma.userShopAccess.deleteMany(),
    prisma.barbershopModule.deleteMany(),
    prisma.barbershopFaq.deleteMany(),
    prisma.barbershopHeroSettings.deleteMany(),
    prisma.barbershopPlansContent.deleteMany(),
    prisma.barbershopAsset.deleteMany(),
    prisma.auditLog.deleteMany(),
    prisma.user.deleteMany(),
    prisma.barbershop.deleteMany(),
  ]);

  console.log('✅ Dados antigos removidos\n');

  console.log('👑 Criando Conta de Acesso Seguro do Super Admin...');
  
  // Lê a senha da variável de ambiente ou cria uma forte e aleatória
  let password = process.env.SUPERADMIN_PASSWORD;
  let isAutoGenerated = false;

  if (!password) {
    password = crypto.randomBytes(8).toString('hex'); // Gera uma senha aleatória de 16 caracteres hex
    isAutoGenerated = true;
  }
  
  const passwordHash = await bcrypt.hash(password, BCRYPT_SALT);

  const superAdmin = await prisma.user.create({
    data: {
      name: 'Super Admin',
      email: process.env.SUPERADMIN_EMAIL || 'superadmin@klypbarber.com',
      phone: '(00) 00000-0000',
      passwordHash,
      role: UserRole.SUPER_ADMIN,
    },
  });

  console.log(`✅ Conta Super Admin criada com sucesso!\n`);
  
  if (isAutoGenerated) {
    console.log(`======================================================`);
    console.log(`⚠️  ATENÇÃO: SENHA SEGURA GERADA AUTOMATICAMENTE ⚠️`);
    console.log(`======================================================`);
    console.log(`📧 E-mail de Login : ${superAdmin.email}`);
    console.log(`🔑 Senha Segura    : ${password}`);
    console.log(`------------------------------------------------------`);
    console.log(`Guarde esta senha num gerenciador de senhas. Ela NÃO será`);
    console.log(`mostrada novamente. Para definir manualmente a senha nas`);
    console.log(`próximas vezes, defina a var de ambiente SUPERADMIN_PASSWORD.`);
    console.log(`======================================================\n`);
  } else {
    console.log(`======================================================`);
    console.log(`📧 E-mail de Login : ${superAdmin.email}`);
    console.log(`🔑 Senha           : [Fornecida via SUPERADMIN_PASSWORD]`);
    console.log(`======================================================\n`);
  }

  console.log('🎉 Seed de Produção finalizado.');
}

main()
  .catch((e) => {
    console.error('❌ Falha ao executar o Seed de Produção:');
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
