import { PrismaClient, UserRole } from '@prisma/client';
import * as bcrypt from 'bcrypt';
import * as crypto from 'crypto';

const prisma = new PrismaClient();
const BCRYPT_SALT = 12;

async function main() {
  console.log('🌱 Iniciando seed de PRODUÇÃO do banco de dados...\n');
  console.log('⚠️  ATENÇÃO: Este script apagará todos os dados do banco de dados se houver!\n');

  // Limpiar dados existentes ordenados para não quebrar Constraints de Foreign Keys
  await prisma.$transaction([
    prisma.appointmentService.deleteMany(),
    prisma.appointmentProduct.deleteMany(),
    prisma.invoiceItem.deleteMany(),
    prisma.orderItem.deleteMany(),
    prisma.barberCommission.deleteMany(),
    prisma.agendaLock.deleteMany(),
    prisma.blockedTime.deleteMany(),
    prisma.review.deleteMany(),
    prisma.notificationLog.deleteMany(),
    prisma.productStockMovement.deleteMany(),
    prisma.serviceDisabledPeriod.deleteMany(),
    prisma.serviceProductAnalytics.deleteMany(),
    prisma.serviceOrder.deleteMany(),
    prisma.invoice.deleteMany(),
    prisma.appointment.deleteMany(),
    prisma.dailyCashFlow.deleteMany(),
    prisma.expense.deleteMany(),
    prisma.fixedCost.deleteMany(),
    prisma.supplyItem.deleteMany(),
    prisma.address.deleteMany(),
    prisma.favoriteBarbershop.deleteMany(),
    prisma.product.deleteMany(),
    prisma.service.deleteMany(),
    prisma.plan.deleteMany(),
    prisma.barber.deleteMany(),
    prisma.client.deleteMany(),
    prisma.userShopAccess.deleteMany(),
    prisma.barbershopModule.deleteMany(),
    prisma.barbershopFaq.deleteMany(),
    prisma.barbershopHeroSettings.deleteMany(),
    prisma.barbershopPlansContent.deleteMany(),
    prisma.barbershopAsset.deleteMany(),
    prisma.auditLog.deleteMany(),
    prisma.user.deleteMany(),
    prisma.barbershop.deleteMany(),
  ]);

  console.log('✅ Dados antigos removidos\n');

  console.log('👑 Criando Conta de Acesso Seguro do Super Admin...');
  
  // Lê a senha da variável de ambiente ou cria uma forte e aleatória
  let password = process.env.SUPERADMIN_PASSWORD;
  let isAutoGenerated = false;

  if (!password) {
    password = crypto.randomBytes(8).toString('hex'); // Gera uma senha aleatória de 16 caracteres hex
    isAutoGenerated = true;
  }
  
  const passwordHash = await bcrypt.hash(password, BCRYPT_SALT);

  const superAdmin = await prisma.user.create({
    data: {
      name: 'Super Admin',
      email: process.env.SUPERADMIN_EMAIL || 'superadmin@klypbarber.com',
      phone: '(00) 00000-0000',
      passwordHash,
      role: UserRole.SUPER_ADMIN,
    },
  });

  console.log(`✅ Conta Super Admin criada com sucesso!\n`);
  
  if (isAutoGenerated) {
    console.log(`======================================================`);
    console.log(`⚠️  ATENÇÃO: SENHA SEGURA GERADA AUTOMATICAMENTE ⚠️`);
    console.log(`======================================================`);
    console.log(`📧 E-mail de Login : ${superAdmin.email}`);
    console.log(`🔑 Senha Segura    : ${password}`);
    console.log(`------------------------------------------------------`);
    console.log(`Guarde esta senha num gerenciador de senhas. Ela NÃO será`);
    console.log(`mostrada novamente. Para definir manualmente a senha nas`);
    console.log(`próximas vezes, defina a var de ambiente SUPERADMIN_PASSWORD.`);
    console.log(`======================================================\n`);
  } else {
    console.log(`======================================================`);
    console.log(`📧 E-mail de Login : ${superAdmin.email}`);
    console.log(`🔑 Senha           : [Fornecida via SUPERADMIN_PASSWORD]`);
    console.log(`======================================================\n`);
  }

  console.log('💈 Criando barbearias reais (StudioJBlack e Barbearia de Oz)...');

  const shop1 = await prisma.barbershop.create({
    data: {
      name: 'StudioJBlack',
      cnpj: '11.111.111/0001-11',
      phone: '(11) 99999-1111',
      address: 'Rua Principal do Studio JBlack, 100',
      openingTime: '09:00',
      closingTime: '20:00',
      intervalMinutes: 30,
      active: true,
      subscriptionTier: 'PREMIUM',
      heroSettings: {
        create: {
          title: 'Estilo & Tradição',
          subtitle: 'StudioJBlack - Excelência no atendimento',
        }
      }
    }
  });

  const shop2 = await prisma.barbershop.create({
    data: {
      name: 'Barbearia de Oz',
      cnpj: '22.222.222/0001-22',
      phone: '(11) 99999-2222',
      address: 'Avenida Mágica de Oz, 200',
      openingTime: '09:00',
      closingTime: '20:00',
      intervalMinutes: 30,
      active: true,
      subscriptionTier: 'PREMIUM',
      heroSettings: {
        create: {
          title: 'A Mais Mágica',
          subtitle: 'Barbearia de Oz - O seu estilo',
        }
      }
    }
  });

  // Vinculando acesso do SuperAdmin às duas lojas
  await prisma.userShopAccess.createMany({
    data: [
      { userId: superAdmin.id, shopId: shop1.id, role: UserRole.SUPER_ADMIN },
      { userId: superAdmin.id, shopId: shop2.id, role: UserRole.SUPER_ADMIN }
    ]
  });

  console.log(`✅ Barbearias criadas e atreladas ao admin!\n`);

  console.log('✂️ Criando serviços base de exemplo nas barbearias...');
  
  const baseServices = [
    { name: 'Corte Degradê', duration: 45, price: 45, category: 'Cortes' },
    { name: 'Barba Terapia', duration: 45, price: 35, category: 'Barba' },
    { name: 'Corte Infantil', duration: 30, price: 30, category: 'Cortes' },
  ];

  for (const s of baseServices) {
    await prisma.service.create({ data: { ...s, shopId: shop1.id } });
    await prisma.service.create({ data: { ...s, shopId: shop2.id } });
  }

  console.log('📦 Criando produtos base nas barbearias...');

  const baseProducts = [
    { name: 'Pomada Modeladora', price: 40, stock: 20, category: 'Finalizadores' },
    { name: 'Óleo para Barba', price: 35, stock: 15, category: 'Cuidados' },
  ];

  for (const p of baseProducts) {
    await prisma.product.create({ data: { ...p, shopId: shop1.id } });
    await prisma.product.create({ data: { ...p, shopId: shop2.id } });
  }

  console.log('🎉 Seed de Produção finalizado com as lojas StudioJBlack e Barbearia de Oz!');
}

main()
  .catch((e) => {
    console.error('❌ Falha ao executar o Seed de Produção:');
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

