export enum NotificationType {
  NEW_APPOINTMENT = 'NEW_APPOINTMENT',
  APPOINTMENT_CANCELLED_BY_CLIENT = 'APPOINTMENT_CANCELLED_BY_CLIENT',
  APPOINTMENT_CANCELLED_BY_BARBER = 'APPOINTMENT_CANCELLED_BY_BARBER',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  SERVICE_ORDER_CREATED = 'SERVICE_ORDER_CREATED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  WHATSAPP = 'WHATSAPP',
}
